# scripts/generate_model_c_array.py
"""Generate a C header file containing the INT8 TFLite model as a byte array.

Outputs:
- firmware/model_data.h with include guards
- Prints model size, array size, SHA256 hashes and verifies them

Usage:
    .\.venv\Scripts\python.exe scripts/generate_model_c_array.py
"""
import os
import sys
import hashlib
import textwrap

# Paths relative to the repository root
MODEL_PATH = os.path.join("models", "tflite", "dscnn_1.0s_int8.tflite")
OUTPUT_DIR = os.path.join("firmware")
HEADER_PATH = os.path.join(OUTPUT_DIR, "model_data.h")

def compute_sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()

def format_c_array(data: bytes, var_name: str) -> str:
    # Split into lines of 12 bytes for readability
    lines = []
    for i in range(0, len(data), 12):
        chunk = data[i:i+12]
        line = ", ".join(str(b) for b in chunk)
        lines.append(line)
    array_body = ",\n    ".join(lines)
    return f"const unsigned char {var_name}[] = {{\n    {array_body}\n}};"

def main():
    if not os.path.exists(MODEL_PATH):
        print(f"[ERROR] Model file not found: {MODEL_PATH}")
        sys.exit(1)
    # Read model bytes
    with open(MODEL_PATH, "rb") as f:
        model_bytes = f.read()
    model_size = len(model_bytes)
    model_sha = compute_sha256(model_bytes)

    # Ensure output directory exists
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # Create C header content
    include_guard = "MODEL_DATA_H"
    array_name = "g_dscnn_model"
    length_name = "g_dscnn_model_len"

    c_array = format_c_array(model_bytes, array_name)
    header_content = textwrap.dedent(f"""
    #ifndef {include_guard}
    #define {include_guard}

    {c_array}
    const unsigned int {length_name} = {model_size};

    #endif // {include_guard}
    """)

    # Write header file
    with open(HEADER_PATH, "w", newline="\n") as out:
        out.write(header_content)

    # Compute SHA256 of the generated byte array (identical to source)
    array_sha = compute_sha256(model_bytes)

    # Print verification info
    print("=== Model to C array conversion ===")
    print(f"Source model size (bytes): {model_size}")
    print(f"Generated array size (bytes): {model_size}")
    print(f"SHA256 of source model: {model_sha}")
    print(f"SHA256 of generated array: {array_sha}")
    if model_sha == array_sha:
        print("SHA256 verification: MATCH")
    else:
        print("SHA256 verification: MISMATCH")
        sys.exit(1)

if __name__ == "__main__":
    main()
